<a href="https://colab.research.google.com/github/prathyu-08/LeetCode/blob/main/miniproject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

In [ ]:
df=pd.read_csv('/content/googleplaystore.csv')
df


Unnamed: 0.1  Unnamed: 0  \
0                0           0   
1                1           1   
2                2           2   
3                3           3   
4                4           4   
...            ...         ...   
9653         10834       10836   
9654         10835       10837   
9655         10836       10838   
9656         10837       10839   
9657         10838       10840   

                                                    App             Category  \
0        Photo Editor & Candy Camera & Grid & ScrapBook       ART_AND_DESIGN   
1                                   Coloring book moana       ART_AND_DESIGN   
2     U Launcher Lite – FREE Live Cool Themes, Hide ...       ART_AND_DESIGN   
3                                 Sketch - Draw & Paint       ART_AND_DESIGN   
4                 Pixel Draw - Number Art Coloring Book       ART_AND_DESIGN   
...                                                 ...                  ...   
9653                                   Sya9a Maroc - FR               FAMILY   
9654                   Fr. Mike Schmitz Audio Teachings               FAMILY   
9655                             Parkinson Exercices FR              MEDICAL   
9656                      The SCP Foundation DB fr nn5n  BOOKS_AND_REFERENCE   
9657      iHoroscope - 2018 Daily Horoscope & Astrology            LIFESTYLE   

      Rating  Reviews  Size  Installs  Type  Price Content Rating  \
0        4.1      159  19.0     10000  Free    0.0       Everyone   
1        3.9      967  14.0    500000  Free    0.0       Everyone   
2        4.7    87510   8.7   5000000  Free    0.0       Everyone   
3        4.5   215644  25.0  50000000  Free    0.0           Teen   
4        4.3      967   2.8    100000  Free    0.0       Everyone   
...      ...      ...   ...       ...   ...    ...            ...   
9653     4.5       38  53.0      5000  Free    0.0       Everyone   
9654     5.0        4   3.6       100  Free    0.0       Everyone   
9655     NaN        3   9.5      1000  Free    0.0       Everyone   
9656     4.5      114   NaN      1000  Free    0.0     Mature 17+   
9657     4.5   398307  19.0  10000000  Free    0.0       Everyone   

                         Genres Last Updated         Current Ver  \
0                  Art & Design   2018-01-07               1.0.0   
1     Art & Design;Pretend Play   2018-01-15               2.0.0   
2                  Art & Design   2018-08-01               1.2.4   
3                  Art & Design   2018-06-08  Varies with device   
4       Art & Design;Creativity   2018-06-20                 1.1   
...                         ...          ...                 ...   
9653                  Education   2017-07-25                1.48   
9654                  Education   2018-07-06                 1.0   
9655                    Medical   2017-01-20                 1.0   
9656          Books & Reference   2015-01-19  Varies with device   
9657                  Lifestyle   2018-07-25  Varies with device   

             Android Ver  
0           4.0.3 and up  
1           4.0.3 and up  
2           4.0.3 and up  
3             4.2 and up  
4             4.4 and up  
...                  ...  
9653          4.1 and up  
9654          4.1 and up  
9655          2.2 and up  
9656  Varies with device  
9657  Varies with device  

[9658 rows x 15 columns]

In [ ]:
df.head()

Unnamed: 0.1  Unnamed: 0  \
0             0           0   
1             1           1   
2             2           2   
3             3           3   
4             4           4   

                                                 App        Category  Rating  \
0     Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN     4.1   
1                                Coloring book moana  ART_AND_DESIGN     3.9   
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN     4.7   
3                              Sketch - Draw & Paint  ART_AND_DESIGN     4.5   
4              Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN     4.3   

   Reviews  Size  Installs  Type  Price Content Rating  \
0      159  19.0     10000  Free    0.0       Everyone   
1      967  14.0    500000  Free    0.0       Everyone   
2    87510   8.7   5000000  Free    0.0       Everyone   
3   215644  25.0  50000000  Free    0.0           Teen   
4      967   2.8    100000  Free    0.0       Everyone   

                      Genres Last Updated         Current Ver   Android Ver  
0               Art & Design   2018-01-07               1.0.0  4.0.3 and up  
1  Art & Design;Pretend Play   2018-01-15               2.0.0  4.0.3 and up  
2               Art & Design   2018-08-01               1.2.4  4.0.3 and up  
3               Art & Design   2018-06-08  Varies with device    4.2 and up  
4    Art & Design;Creativity   2018-06-20                 1.1    4.4 and up

In [ ]:
df.shape

(9658, 15)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9658 entries, 0 to 9657
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Unnamed: 0.1    9658 non-null   int64  
 1   Unnamed: 0      9658 non-null   int64  
 2   App             9658 non-null   object 
 3   Category        9658 non-null   object 
 4   Rating          8195 non-null   float64
 5   Reviews         9658 non-null   int64  
 6   Size            8431 non-null   float64
 7   Installs        9658 non-null   int64  
 8   Type            9657 non-null   object 
 9   Price           9658 non-null   float64
 10  Content Rating  9658 non-null   object 
 11  Genres          9658 non-null   object 
 12  Last Updated    9658 non-null   object 
 13  Current Ver     9650 non-null   object 
 14  Android Ver     9656 non-null   object 
dtypes: float64(3), int64(4), object(8)
memory usage: 1.1+ MB


In [ ]:
df.describe()

Unnamed: 0.1    Unnamed: 0       Rating       Reviews         Size  \
count   9658.000000   9658.000000  8195.000000  9.658000e+03  8431.000000   
mean    5665.600953   5665.675088     4.173337  2.166150e+05    37.136437   
std     3102.018396   3102.137668     0.536589  1.831413e+06   102.420803   
min        0.000000      0.000000     1.000000  0.000000e+00     1.000000   
25%     3111.250000   3111.250000     4.000000  2.500000e+01     5.300000   
50%     5813.500000   5813.500000     4.300000  9.670000e+02    14.000000   
75%     8326.750000   8326.750000     4.500000  2.940800e+04    32.000000   
max    10838.000000  10840.000000     5.000000  7.815831e+07  1020.000000   

           Installs        Price  
count  9.658000e+03  9658.000000  
mean   7.778312e+06     1.099413  
std    5.376100e+07    16.853021  
min    0.000000e+00     0.000000  
25%    1.000000e+03     0.000000  
50%    1.000000e+05     0.000000  
75%    1.000000e+06     0.000000  
max    1.000000e+09   400.000000

In [ ]:
#missing Values
df.isnull().sum()

Unnamed: 0.1         0
Unnamed: 0           0
App                  0
Category             0
Rating            1463
Reviews              0
Size              1227
Installs             0
Type                 1
Price                0
Content Rating       0
Genres               0
Last Updated         0
Current Ver          8
Android Ver          2
dtype: int64

In [ ]:
df.head(2)

Unnamed: 0.1  Unnamed: 0                                             App  \
0             0           0  Photo Editor & Candy Camera & Grid & ScrapBook   
1             1           1                             Coloring book moana   

         Category  Rating  Reviews  Size  Installs  Type  Price  \
0  ART_AND_DESIGN     4.1      159  19.0     10000  Free    0.0   
1  ART_AND_DESIGN     3.9      967  14.0    500000  Free    0.0   

  Content Rating                     Genres Last Updated Current Ver  \
0       Everyone               Art & Design   2018-01-07       1.0.0   
1       Everyone  Art & Design;Pretend Play   2018-01-15       2.0.0   

    Android Ver  
0  4.0.3 and up  
1  4.0.3 and up

In [ ]:
df['Reviews'].unique()

array([   159,    967,  87510, ...,    603,   1195, 398307])

In [ ]:
df['Reviews'].astype(int)

0          159
1          967
2        87510
3       215644
4          967
         ...  
9653        38
9654         4
9655         3
9656       114
9657    398307
Name: Reviews, Length: 9658, dtype: int64

In [ ]:
df['Reviews'].astype(str).str.isnumeric().sum()

np.int64(9658)

In [ ]:
df[~df['Reviews'].astype(str).str.isnumeric()]

Empty DataFrame
Columns: [Unnamed: 0.1, Unnamed: 0, App, Category, Rating, Reviews, Size, Installs, Type, Price, Content Rating, Genres, Last Updated, Current Ver, Android Ver]
Index: []

In [ ]:
df_copy=df.copy()

In [ ]:
df['Reviews'].unique()

array([   159,    967,  87510, ...,    603,   1195, 398307])

In [ ]:
df['Reviews'].astype(int)

0          159
1          967
2        87510
3       215644
4          967
         ...  
9653        38
9654         4
9655         3
9656       114
9657    398307
Name: Reviews, Length: 9658, dtype: int64

In [ ]:
df_copy['Size'].isnull().sum()

np.int64(1227)

In [ ]:
df['Reviews'].astype(str).str.isnumeric().sum()

np.int64(9658)

In [ ]:
df[~df['Reviews'].astype(str).str.isnumeric()]

Empty DataFrame
Columns: [Unnamed: 0.1, Unnamed: 0, App, Category, Rating, Reviews, Size, Installs, Type, Price, Content Rating, Genres, Last Updated, Current Ver, Android Ver]
Index: []

In [ ]:
df_copy=df.copy()

In [ ]:
df_copy=df_copy.drop(df_copy.index[10472])

In [ ]:
df_copy[~df_copy['Reviews'].astype(str).str.isnumeric()]

Empty DataFrame
Columns: [Unnamed: 0.1, Unnamed: 0, App, Category, Rating, Reviews, Size, Installs, Type, Price, Content Rating, Genres, Last Updated, Current Ver, Android Ver]
Index: []

In [ ]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9658 entries, 0 to 9657
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Unnamed: 0.1    9658 non-null   int64  
 1   Unnamed: 0      9658 non-null   int64  
 2   App             9658 non-null   object 
 3   Category        9658 non-null   object 
 4   Rating          8195 non-null   float64
 5   Reviews         9658 non-null   int64  
 6   Size            8431 non-null   float64
 7   Installs        9658 non-null   int64  
 8   Type            9657 non-null   object 
 9   Price           9658 non-null   float64
 10  Content Rating  9658 non-null   object 
 11  Genres          9658 non-null   object 
 12  Last Updated    9658 non-null   object 
 13  Current Ver     9650 non-null   object 
 14  Android Ver     9656 non-null   object 
dtypes: float64(3), int64(4), object(8)
memory usage: 1.1+ MB


In [ ]:
df_copy['Size'].unique()

array([1.90e+01, 1.40e+01, 8.70e+00, 2.50e+01, 2.80e+00, 5.60e+00,
       2.90e+01, 3.30e+01, 3.10e+00, 2.80e+01, 1.20e+01, 2.00e+01,
       2.10e+01, 3.70e+01, 2.70e+00, 5.50e+00, 1.70e+01, 3.90e+01,
       3.10e+01, 4.20e+00, 7.00e+00, 2.30e+01, 6.00e+00, 6.10e+00,
       4.60e+00, 9.20e+00, 5.20e+00, 1.10e+01, 2.40e+01,      nan,
       9.40e+00, 1.50e+01, 1.00e+01, 1.20e+00, 2.60e+01, 8.00e+00,
       7.90e+00, 5.60e+01, 5.70e+01, 3.50e+01, 5.40e+01, 2.01e+02,
       3.60e+00, 5.70e+00, 8.60e+00, 2.40e+00, 2.70e+01, 2.50e+00,
       1.60e+01, 3.40e+00, 8.90e+00, 3.90e+00, 2.90e+00, 3.80e+01,
       3.20e+01, 5.40e+00, 1.80e+01, 1.10e+00, 2.20e+00, 4.50e+00,
       9.80e+00, 5.20e+01, 9.00e+00, 6.70e+00, 3.00e+01, 2.60e+00,
       7.10e+00, 3.70e+00, 2.20e+01, 7.40e+00, 6.40e+00, 3.20e+00,
       8.20e+00, 9.90e+00, 4.90e+00, 9.50e+00, 5.00e+00, 5.90e+00,
       1.30e+01, 7.30e+01, 6.80e+00, 3.50e+00, 4.00e+00, 2.30e+00,
       7.20e+00, 2.10e+00, 4.20e+01, 7.30e+00, 9.10e+00, 5.50e

In [ ]:
df_copy['Size'].isnull().sum()

np.int64(1227)

In [ ]:
df_copy['Size']=df_copy['Size'].str.replace('M','000')
df_copy['Size']=df_copy['Size'].str.replace('k','')
df_copy['Size']=df_copy['Size'].replace('Varies with device',np.nan)
df_copy['Size']=df_copy['Size'].astype(float)

In [ ]:
df_copy['Size']

0       19.0
1       14.0
2        8.7
3       25.0
4        2.8
        ... 
9653    53.0
9654     3.6
9655     9.5
9656     NaN
9657    19.0
Name: Size, Length: 9658, dtype: float64

In [ ]:
df_copy['Installs'].unique()

array([     10000,     500000,    5000000,   50000000,     100000,
            50000,    1000000,   10000000,       5000,  100000000,
       1000000000,       1000,  500000000,         50,        100,
              500,         10,          1,          5,          0])

In [ ]:
df_copy['Price'].unique()

array([  0.  ,   4.99,   3.99,   6.99,   1.49,   2.99,   7.99,   5.99,
         3.49,   1.99,   9.99,   7.49,   0.99,   9.  ,   5.49,  10.  ,
        24.99,  11.99,  79.99,  16.99,  14.99,   1.  ,  29.99,  12.99,
         2.49,  10.99,   1.5 ,  19.99,  15.99,  33.99,  74.99,  39.99,
         3.95,   4.49,   1.7 ,   8.99,   2.  ,   3.88,  25.99, 399.99,
        17.99, 400.  ,   3.02,   1.76,   4.84,   4.77,   1.61,   2.5 ,
         1.59,   6.49,   1.29,   5.  ,  13.99, 299.99, 379.99,  37.99,
        18.99, 389.99,  19.9 ,   8.49,   1.75,  14.  ,   4.85,  46.99,
       109.99, 154.99,   3.08,   2.59,   4.8 ,   1.96,  19.4 ,   3.9 ,
         4.59,  15.46,   3.04,   4.29,   2.6 ,   3.28,   4.6 ,  28.99,
         2.95,   2.9 ,   1.97, 200.  ,  89.99,   2.56,  30.99,   3.61,
       394.99,   1.26,   1.2 ,   1.04])

In [ ]:
chars_to_remove=['+',',','$']
cols_to_clean=['Installs','Price']
for item in chars_to_remove:
    for cols in cols_to_clean:
        df_copy[cols]=df_copy[cols].str.replace(item,'')

In [ ]:
df_copy['Installs'].unique()

array([     10000,     500000,    5000000,   50000000,     100000,
            50000,    1000000,   10000000,       5000,  100000000,
       1000000000,       1000,  500000000,         50,        100,
              500,         10,          1,          5,          0])

In [ ]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9658 entries, 0 to 9657
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Unnamed: 0.1    9658 non-null   int64  
 1   Unnamed: 0      9658 non-null   int64  
 2   App             9658 non-null   object 
 3   Category        9658 non-null   object 
 4   Rating          8195 non-null   float64
 5   Reviews         9658 non-null   int64  
 6   Size            8431 non-null   float64
 7   Installs        9658 non-null   int64  
 8   Type            9657 non-null   object 
 9   Price           9658 non-null   float64
 10  Content Rating  9658 non-null   object 
 11  Genres          9658 non-null   object 
 12  Last Updated    9658 non-null   object 
 13  Current Ver     9650 non-null   object 
 14  Android Ver     9656 non-null   object 
dtypes: float64(3), int64(4), object(8)
memory usage: 1.1+ MB


In [ ]:
df_copy['Price'].unique()

array([  0.  ,   4.99,   3.99,   6.99,   1.49,   2.99,   7.99,   5.99,
         3.49,   1.99,   9.99,   7.49,   0.99,   9.  ,   5.49,  10.  ,
        24.99,  11.99,  79.99,  16.99,  14.99,   1.  ,  29.99,  12.99,
         2.49,  10.99,   1.5 ,  19.99,  15.99,  33.99,  74.99,  39.99,
         3.95,   4.49,   1.7 ,   8.99,   2.  ,   3.88,  25.99, 399.99,
        17.99, 400.  ,   3.02,   1.76,   4.84,   4.77,   1.61,   2.5 ,
         1.59,   6.49,   1.29,   5.  ,  13.99, 299.99, 379.99,  37.99,
        18.99, 389.99,  19.9 ,   8.49,   1.75,  14.  ,   4.85,  46.99,
       109.99, 154.99,   3.08,   2.59,   4.8 ,   1.96,  19.4 ,   3.9 ,
         4.59,  15.46,   3.04,   4.29,   2.6 ,   3.28,   4.6 ,  28.99,
         2.95,   2.9 ,   1.97, 200.  ,  89.99,   2.56,  30.99,   3.61,
       394.99,   1.26,   1.2 ,   1.04])

In [ ]:
df_copy['Last Updated'].unique()

array(['2018-01-07', '2018-01-15', '2018-08-01', ..., '2014-01-20',
       '2014-02-16', '2014-03-23'], dtype=object)

In [ ]:
df_copy['Last Updated']=pd.to_datetime(df_copy['Last Updated'])
df_copy['Day']=df_copu['Last Updated'].dt.Day
df_copy['Month']=df_copy['Last Updated'].dt.Month
df_copy['Year']=df_copy['Last Updated''].dt.year

In [ ]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9658 entries, 0 to 9657
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Unnamed: 0.1    9658 non-null   int64  
 1   Unnamed: 0      9658 non-null   int64  
 2   App             9658 non-null   object 
 3   Category        9658 non-null   object 
 4   Rating          8195 non-null   float64
 5   Reviews         9658 non-null   int64  
 6   Size            8431 non-null   float64
 7   Installs        9658 non-null   int64  
 8   Type            9657 non-null   object 
 9   Price           9658 non-null   float64
 10  Content Rating  9658 non-null   object 
 11  Genres          9658 non-null   object 
 12  Last Updated    9658 non-null   object 
 13  Current Ver     9650 non-null   object 
 14  Android Ver     9656 non-null   object 
dtypes: float64(3), int64(4), object(8)
memory usage: 1.1+ MB


In [ ]:
df_copy.to_csv('/content/googleplaystore.csv')

In [ ]:
df_copy.head()

Unnamed: 0.1  Unnamed: 0  \
0             0           0   
1             1           1   
2             2           2   
3             3           3   
4             4           4   

                                                 App        Category  Rating  \
0     Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN     4.1   
1                                Coloring book moana  ART_AND_DESIGN     3.9   
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN     4.7   
3                              Sketch - Draw & Paint  ART_AND_DESIGN     4.5   
4              Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN     4.3   

   Reviews  Size  Installs  Type  Price Content Rating  \
0      159  19.0     10000  Free    0.0       Everyone   
1      967  14.0    500000  Free    0.0       Everyone   
2    87510   8.7   5000000  Free    0.0       Everyone   
3   215644  25.0  50000000  Free    0.0           Teen   
4      967   2.8    100000  Free    0.0       Everyone   

                      Genres Last Updated         Current Ver   Android Ver  
0               Art & Design   2018-01-07               1.0.0  4.0.3 and up  
1  Art & Design;Pretend Play   2018-01-15               2.0.0  4.0.3 and up  
2               Art & Design   2018-08-01               1.2.4  4.0.3 and up  
3               Art & Design   2018-06-08  Varies with device    4.2 and up  
4    Art & Design;Creativity   2018-06-20                 1.1    4.4 and up

In [ ]:
df_copy[df_copy.duplicated('App')].shape

(0, 15)

In [ ]:
df_copy=df_copy.drop_duplicates(subset=['App'],keep='first')

In [ ]:
df_copy.shape

(9658, 15)

In [ ]:
numeric_features = [feature for feature in df_copy.columns if df_copy[feature].dtype != 'O']
categorical_features = [feature for feature in df_copy.columns if df_copy[feature].dtype == 'O']

# print columns
print('We have {} numerical features : {}'.format(len(numeric_features), numeric_features))
print('\nWe have {} categorical features : {}'.format(len(categorical_features), categorical_features))

We have 7 numerical features : ['Unnamed: 0.1', 'Unnamed: 0', 'Rating', 'Reviews', 'Size', 'Installs', 'Price']

We have 8 categorical features : ['App', 'Category', 'Type', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver', 'Android Ver']
