<a href="https://colab.research.google.com/github/prathyu-08/Day1.ipynb/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
arr=np.zeros(3)
print(arr)

[0. 0. 0.]


In [3]:
import numpy as np
arr=np.ones(6)
print(arr)

[1. 1. 1. 1. 1. 1.]


In [4]:
import numpy as np
arr=np.ones((3,5))
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [10]:
import numpy as np
arr=np.zeros((3,4), order='F')
print(arr)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
import numpy as np
arr=np.array(([1,2,3], [4,5,6], [7,8,9]))
row=[7,9,6]
print(row in arr.tolist())

False
